# ===========================================
# STRESS TEST SENARYOLARI
# CPU, Memory ve I/O stres testleri
# ===========================================

---
# Senaryo 1: Yüksek CPU Stresi - Payment Service
apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: cpu-stress-payment
  namespace: payment-chaos
  labels:
    experiment: stress
    severity: high
spec:
  mode: all
  selector:
    namespaces:
      - payment-chaos
    labelSelectors:
      app: payment-service
  stressors:
    cpu:
      workers: 2 # 2 CPU worker
      load: 80 # %80 CPU kullanımı
  duration: "5m"

---
# Senaryo 2: %100 CPU - Tam Yük
apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: cpu-stress-100-percent
  namespace: payment-chaos
  labels:
    experiment: stress
    severity: critical
spec:
  mode: one # Rastgele bir pod
  selector:
    namespaces:
      - payment-chaos
    labelSelectors:
      app: payment-service
  stressors:
    cpu:
      workers: 4
      load: 100 # %100 CPU
  duration: "3m"

---
# Senaryo 3: Memory Stresi - Inventory Service
apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: memory-stress-inventory
  namespace: payment-chaos
  labels:
    experiment: stress
    severity: high
spec:
  mode: all
  selector:
    namespaces:
      - payment-chaos
    labelSelectors:
      app: inventory-service
  stressors:
    memory:
      workers: 2
      size: "100MB" # 100MB bellek kullan
  duration: "5m"

---
# Senaryo 4: CPU + Memory Kombine Stres
apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: combined-stress-payment
  namespace: payment-chaos
  labels:
    experiment: stress
    severity: critical
spec:
  mode: all
  selector:
    namespaces:
      - payment-chaos
    labelSelectors:
      app: payment-service
  stressors:
    cpu:
      workers: 2
      load: 70 # %70 CPU
    memory:
      workers: 1
      size: "80MB" # 80MB bellek
  duration: "5m"

---
# Senaryo 5: Zamanlanmış CPU Stresi
apiVersion: chaos-mesh.org/v1alpha1
kind: Schedule
metadata:
  name: scheduled-cpu-stress
  namespace: payment-chaos
spec:
  schedule: "*/5 * * * *" # Her 5 dakikada bir
  type: StressChaos
  historyLimit: 5
  concurrencyPolicy: Forbid
  stressChaos:
    mode: one
    selector:
      namespaces:
        - payment-chaos
      labelSelectors:
        app: payment-service
    stressors:
      cpu:
        workers: 2
        load: 90 # %90 CPU
    duration: "2m"

---
# Senaryo 6: Kademeli Stres Artışı Workflow
apiVersion: chaos-mesh.org/v1alpha1
kind: Workflow
metadata:
  name: gradual-stress-increase
  namespace: payment-chaos
spec:
  entry: stress-sequence
  templates:
    - name: stress-sequence
      templateType: Serial
      deadline: "15m"
      children:
        - low-stress
        - medium-stress
        - high-stress

    - name: low-stress
      templateType: StressChaos
      deadline: "3m"
      stressChaos:
        mode: all
        selector:
          namespaces:
            - payment-chaos
          labelSelectors:
            app: payment-service
        stressors:
          cpu:
            workers: 1
            load: 30 # %30 CPU

    - name: medium-stress
      templateType: StressChaos
      deadline: "3m"
      stressChaos:
        mode: all
        selector:
          namespaces:
            - payment-chaos
          labelSelectors:
            app: payment-service
        stressors:
          cpu:
            workers: 2
            load: 60 # %60 CPU

    - name: high-stress
      templateType: StressChaos
      deadline: "3m"
      stressChaos:
        mode: all
        selector:
          namespaces:
            - payment-chaos
          labelSelectors:
            app: payment-service
        stressors:
          cpu:
            workers: 3
            load: 90 # %90 CPU
